<h1>
    <?php
	echo "$count HTTP Transfers";
    if ($count > 0) {
        echo ', ' . \round($totalDuration * 1000,1) . ' ms';
	}
	?>
</h1>
<div class="tracy-inner"><div class="tracy-inner-container">
	<table>
        <colgroup>
            <col width="70px" />
        </colgroup>
		<tbody>
		<?php
		foreach ($logs as $logKey => $log) {
			$request = $log->getRequest();
			$response = $log->getResponse();
			$exception = $log->getException();
			$requestBody = (string)$request->getBody();
			$responseBody = isset($response) ? ((string)$response->getBody()) : '';
			$duration = \round(($log->getEndTime() - $log->getStartTime()) * 1000, 1);
			$context = $log->getContext();
			?>
			<?php
			if (isset($request)) {
				?>
                <tr>
                    <th colspan="2"><?php echo $request->getMethod() . ' ' . $request->getUri();?></th>
                </tr>
                <?php if (isset($response)) { ?>
                <tr>
                    <th colspan="2"><?php echo $response->getStatusCode() . ' ' . $response->getReasonPhrase();?></th>
                </tr>
                <?php } ?>
                <tr>
                    <td><?php if (isset($duration)) echo $duration . ' ms'; ?></td>
                    <td>
                        <a class="tracy-toggle tracy-collapsed" data-tracy-ref="^table .request-headers-<?php echo $logKey;?>">Request Headers</a>
						<?php if ($requestBody != '') echo '<a class="tracy-toggle tracy-collapsed" data-tracy-ref="^table .request-body-' . $logKey . '">Request Body</a>'; ?>

                        <?php if (isset($response)) { ?>
                        <a class="tracy-toggle tracy-collapsed" data-tracy-ref="^table .response-headers-<?php echo $logKey;?>">Response Headers</a>
						<?php if ($responseBody != '') echo '<a class="tracy-toggle tracy-collapsed" data-tracy-ref="^table .response-body-' . $logKey . '">Response Body</a>'; ?>
                        <?php } ?>
                    </td>
                </tr>
				<tr class="request-headers-<?php echo $logKey;?> tracy-collapsed">
					<td>Request Headers</td>
					<td style="word-wrap: break-word;">
						<?php
						foreach ($request->getHeaders() as $key => $value) {
							if (\is_array($value)) {
								foreach ($value as $v) {
									echo '<strong>' . $key . ': </strong>' . $v . '<br/>';
								}
							} else {
								echo '<strong>' . $key . ': </strong>' . $value . '<br/>';
							}

						}
						?>
					</td>
				</tr>
				<?php
				if ($requestBody != '') {
					?>
					<tr class="request-body-<?php echo $logKey;?> tracy-collapsed">
						<td>Request Body</td>
						<td><?php echo htmlspecialchars($requestBody, \ENT_SUBSTITUTE); ?></td>
					</tr>
					<?php
				}
			}
			if (isset($response)) {
				?>
				<tr class="response-headers-<?php echo $logKey;?> tracy-collapsed">
					<td>Response Headers</td>
					<td style="word-wrap: break-word; max-width: 600px;">
						<?php
						foreach ($response->getHeaders() as $key => $value) {
							if (\is_array($value)) {
								foreach ($value as $v) {
									echo '<strong>' . $key . ': </strong>' . $v . '<br/>';
								}
							} else {
								echo '<strong>' . $key . ': </strong>' . $value . '<br/>';
							}

						}
						?>
					</td>
				</tr>
				<?php
				if ($responseBody != '') {
					?>
					<tr class="response-body-<?php echo $logKey;?> tracy-collapsed">
						<td>Response Body</td>
						<td style="word-wrap: break-word; max-width: 600px;">
                            <?php echo htmlspecialchars($responseBody, \ENT_SUBSTITUTE); ?>
						</td>
					</tr>
					<?php
				}
			}
			if (isset($exception)) {
				?>
                <tr>
                    <td>Error</td>
                    <td><?php echo \Tracy\Dumper::toHtml($exception, ['collapse' => true]); ?></td>
                </tr>
				<?php
			}
			if (!empty($context)) {
				?>
                <tr>
                    <td>Context</td>
                    <td><?php echo \Tracy\Dumper::toHtml($context, ['collapse' => true]); ?></td>
                </tr>
				<?php
			}
		}
		?>
		</tbody>
	</table>
    </div></div>